name: Dev Environment Workflow

on:
  push:
    branches: [master]
    paths:
      - dev/**

jobs:
  Publish-Content:
    runs-on: ubuntu-latest
    environment:
      name: Dev
    steps:
      - name: Sync from S3
        run: |
          pwd
          mkdir $ENV
          cd $ENV
          aws s3 sync s3://$BUCKET_NAME .
        env:
          ENV: dev
          AWS_DEFAULT_REGION: us-gov-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: cg-df042f58-b01a-4ed0-bd93-54aa07305327
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Sync to S3
        run: |
          pwd
          cd $ENV
          aws s3 sync . s3://$BUCKET_NAME
        env:
          ENV: dev
          AWS_DEFAULT_REGION: us-gov-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: cg-df042f58-b01a-4ed0-bd93-54aa07305327
